### ISSUE TITLE
helper named 'gravatar-image' could not be found

### ISSUE THREAD

**Issue by devinrhode2** [johnotander/ember-cli-gravatar#44]
My template:
```hbs
<div>
  {{gravatar-image email="devinrhode2@gmail.com"
    alt='gravatar image! <3'
    defaultImage='identicon'
    class='img-circle'
    secure=false
    size=250}}
</div>
```

My error:
```
"Error: Assertion Failed: A helper named 'gravatar-image' could not be found
  at new Error (native)
  at Error.EmberError (http://localhost:4200/assets/vendor.js:26419:21)
  at assert (http://localhost:4200/assets/vendor.js:16480:13) 
  at Object.assert (http://localhost:4200/assets/vendor.js:26189:34) 
  at Object.lookupHelper [as default] (http://localhost:4200/assets/vendor.js:22236:22) 
  at Object.lookupHelperHook [as lookupHelper] (http://localhost:4200/assets/vendor.js:19110:52) 
  at Object.inline (http://localhost:4200/assets/vendor.js:57586:30) 
  at Object.AlwaysDirtyVisitor.inline (http://localhost:4200/assets/vendor.js:58100:17) 
  at RenderResult.populateNodes (http://localhost:4200/assets/vendor.js:58520:19) 
  at RenderResult.render (http://localhost:4200/assets/vendor.js:58455:10)"
```

I'm on Ember 2.2 (cli 1.13.13..)
ember-cli-gravatar v 3.4.0

**Comment by devinrhode2** [comment]
Going to try reinstalling dep's

**Comment by devinrhode2** [comment]
reinstalling seems to have fixed it.

**Comment by johnotander** [comment]
Glad you got to the bottom of it! :smile_cat:

**Comment by devinrhode2** [comment]
Now if anyone google's this bug they'll get this :dancers:

**Comment by sandinosaso** [comment]
I am having this same error I just did ```ember install ember-cli-gravatar```
is there anything else required to make it work?

Thank you

**Comment by johnotander** [comment]
Often times it's an issue that has occurred with installation and/or not restarting the ember server. You can try the following steps and then let me know if you're still having problems:

```sh
# Turn of ember server
$ npm uninstall --save-dev ember-cli-gravatar
$ npm cache clean
$ ember install ember-cli-gravatar
$ ember s
```

**Comment by sandinosaso** [comment]
Woooowww

Thank you for so fast answer I was just writing to anyone that 
executing ```ember install ember-cli-gravatar``` again solved it.
I also shutdown the server on started again.

Thank you a lot @johnotander for this great extension I am using it with AdminLTE template and it rocks!!

**Comment by johnotander** [comment]
:+1: :heart_decoration: :rocket:
